use serde::Deserialize;

#[derive(Clone, Debug, Deserialize)]
pub struct Channel {
    pub id: String,
    pub name: String,
    pub handle: String,
    pub avatar_url: String,
}

fn ch(id: &str, name: &str, handle: &str, avatar: &str) -> Channel {
    Channel {
        id: id.into(),
        name: name.into(),
        handle: handle.into(),
        avatar_url: avatar.into(),
    }
}

// Matches the client web app's CHANNELS list (ChannelSidebar.jsx)
pub fn get_channels() -> Vec<Channel> {
    vec![
        ch("amixem", "Amixem", "Amixem",
            "https://yt3.googleusercontent.com/mkxR4YNTUBJAjuq020488wM8yHSCZ4Kwn0etJyYyGTL86LnEiIzu5uhw8EwmPpRxavKYXyQ4Hmk=s160-c-k-c0x00ffffff-no-rj"),
        ch("squeezie", "Squeezie", "Squeezie",
            "https://yt3.googleusercontent.com/ytc/AIdro_mPZvx-xk6pbAYdC7G8jUZzgCNDDTg1ZfF0_Lwd8UpJT4M=s160-c-k-c0x00ffffff-no-rj"),
        ch("mcfly-carlito", "Mcfly et Carlito", "McflyCarlito",
            "https://yt3.googleusercontent.com/ytc/AIdro_kSPG3h89eFoHhkLFYl_VQ6OkFpLCfpZUSuIWkRJt0sI-E=s160-c-k-c0x00ffffff-no-rj"),
        ch("pierre-chabrier", "Pierre Chabrier", "PierreChabrier", ""),
        ch("vilebrequin", "Vilebrequin", "Vilebrequin",
            "https://yt3.googleusercontent.com/ytc/AIdro_mEdBuj1fCqUVLlvdLxIQtLZvUBN3cD-fB7LrYY9Gug65M=s160-c-k-c0x00ffffff-no-rj"),
        ch("pierre-croce", "Pierre Croce", "PierreCroceOff",
            "https://yt3.googleusercontent.com/nITpEppzrNhVmiOCzBsmwQdjzaJ-qJnz4KKwqhbfXgTxdAkKP8ITAz3dlmdIOLPnm4nyxBdbOA=s160-c-k-c0x00ffffff-no-rj"),
        ch("sylvain-lyve", "Sylvain Lyve", "SylvainLyve",
            "https://yt3.googleusercontent.com/VIUzUgC_byAkR-ZVQkcTNeu1bV2DL1r4edu993uQwKMwh14vrffbnZJUKRTM-G6-JVac1d8Vd2E=s160-c-k-c0x00ffffff-no-rj"),
        ch("gmk", "GMK", "GMK",
            "https://yt3.googleusercontent.com/dUPQNmo-biSznsRa11lPuU4LMJIMCfGYspvm0eDwxh0poHr7-0BoLSc0Sx6bvW2LTUk5m1nMWg=s160-c-k-c0x00ffffff-no-rj"),
        ch("thierry-vigneau", "Thierry Vigneau Boiserie", "ThierryVigneauBoiserie",
            "https://yt3.googleusercontent.com/oKx9FZWczFvYXqqRpEEBvJ1K-oCyN1n1hzq-_hGlq5Kqtq4d09MQf1_zG_DqZ4vjK1WYqdRU=s160-c-k-c0x00ffffff-no-rj"),
        ch("inoxtag", "Inoxtag", "inoxtag",
            "https://yt3.googleusercontent.com/ytc/AIdro_nBv_ScBglsYmGLCeX8gG5E7_rC-p9M0I4hQAcEMaHjJa4=s160-c-k-c0x00ffffff-no-rj"),
        ch("michou", "Michou", "MichouOff",
            "https://yt3.googleusercontent.com/AbT6_C0E4bzscwpKqfdeMg6wTCuo_5pP9lkeqcLBFtqbgJsf8GaRGBAUnf7ZuNwEuiTHA7fI=s160-c-k-c0x00ffffff-no-rj"),
        ch("anyme", "Anyme", "Anyme",
            "https://yt3.ggpht.com/dDEFIyDIjJwDz4rDzR5uPCkX0vxqZV3BkIqLYOo0toZiwqxRPjchDMt6ue4jQKF4tkqzQ9nV4Q=s160-c-k-c0x00ffffff-no-rj"),
        ch("diablox9", "DiabloX9", "DiabloX9",
            "https://yt3.ggpht.com/uMCOWq8avyw0TmjgFXjbcKhIucrIL_Nrs9CfqT05DjMXiXtHHjWXe9Rzwoqokyp4kmCnVEV9Qg=s160-c-k-c0x00ffffff-no-rj"),
        ch("frigiel", "Frigiel", "Frigiel",
            "https://yt3.ggpht.com/ytc/AIdro_kgShYZ1YzaXOBkKZVcNEIFsG0gW8f7lRBSa6Iiztcm_OE=s160-c-k-c0x00ffffff-no-rj"),
        ch("arte", "Arte", "ARTE",
            "https://yt3.ggpht.com/JvG9t1fNgirmoEWieadI9gz5wm0889z8ULzCF959u1FrDykh8LJUO9BjEGUg1k_xDOZWFNb3uQ=s160-c-k-c0x00ffffff-no-rj"),
        ch("cest-pas-sorcier", "C'est pas sorcier", "cestpassorcier-TV",
            "https://yt3.ggpht.com/ytc/AIdro_mM6iBpwKwzyyA6sGUzXdRgJbsEY_9RzW5m8GCkbqwgoHM=s160-c-k-c0x00ffffff-no-rj"),
        ch("jamy-epicurieux", "Jamy Epicurieux", "JamyEpicurieux",
            "https://yt3.ggpht.com/PmI8M3fQcLUOPc9oU6PO86lVIdlqwQPQ5K4T_s5YWOei67zPRJ1Knq6pzKawZNWh2Ls7H4w2Dg=s160-c-k-c0x00ffffff-no-rj"),
        ch("le-monde-de-jamy", "Le Monde de Jamy", "LeMondedeJamy",
            "https://yt3.ggpht.com/xnS1GlkSxjq4gSCszvOZs2JXukVrLQ_PvJS1D8qD-kGlQWAmRd2FclWf9Os0lBx6U8JsMqWoVg=s160-c-k-c0x00ffffff-no-rj"),
        ch("matt-stefani", "Matthieu Stefani", "matthieustefani",
            "https://yt3.ggpht.com/D9-xM4azak3iUUib_iSu0TF40VzHKOWIXX_nZD7KaSVd6bDwNMZo4buthDCAr35n10ldm4lD=s160-c-k-c0x00ffffff-no-rj"),
        ch("le-grand-jd", "Le Grand JD", "LeGrandJD",
            "https://yt3.ggpht.com/ytc/AIdro_l4Pra23FO6-vPtWRXDhtSjnuSQnLF4SGsipS0Lh1MndPk=s160-c-k-c0x00ffffff-no-rj"),
        ch("etienne-moustache", "Etienne Moustache", "EtienneMoustache",
            "https://yt3.ggpht.com/MQbyH0jbmKUyIHKJH4RwADwfX-EE28ZLq0eWtCOEEvdBabEv79gIZOO7r6ecG4DA86QVed21zQ=s160-c-k-c0x00ffffff-no-rj"),
        ch("ivan-casta", "Ivan Casta", "IvanCasta",
            "https://yt3.ggpht.com/4E00nf58e3F2Jn3IqIGA7iPBkBjqRmPLKQ-zYEEQgHu8B5TJUP5i5URYomT_1DaCwPf_vruBlg=s160-c-k-c0x00ffffff-no-rj"),
        ch("swan-neo", "Swan et Néo", "SwanetNeo",
            "https://yt3.ggpht.com/ytc/AIdro_lb76hFbhH9PZ0XW0euU91CkBnzsWNNvah-eNa4KbtaiwY=s160-c-k-c0x00ffffff-no-rj"),
        ch("fuze-iii", "Fuze III", "FuzeIII",
            "https://yt3.ggpht.com/3aC7WFMmbNW9pCriWmkLfTxx8hl_YrMQKNcmfaizLRD6v_Nt3Qmn6jAnl7XxFYfKGJzfj0EUQlE=s160-c-k-c0x00ffffff-no-rj"),
        ch("joyca", "Joyca", "joyca",
            "https://yt3.ggpht.com/F5R-8dCR4OsDu1Rs_2RE20e6LUNFDJW6VemSqToit8XvdfoSj1DXJXb0Dc4aT_YEv-5TsFCF=s160-c-k-c0x00ffffff-no-rj"),
        ch("legend", "Legend", "Legend",
            "https://yt3.ggpht.com/xS5_gZPfxkt8cXOIhWBNxKKAxDJst3Pe7TwaF-lhfbfOIB7Ctyt2R5YE6tNIfiZJpGsdyRG-=s160-c-k-c0x00ffffff-no-rj"),
        ch("eloy-spinnler", "Eloy Spinnler", "eloyspinnler",
            "https://yt3.ggpht.com/xBchl3UURdXsU88En-MX7ZvEIfWCRvJBxRtYQtaV8kMt6ET7loexyxiRGqUwVKGxivtqMBBr-w=s160-c-k-c0x00ffffff-no-rj"),
        ch("52-minutes", "52 Minutes RTS", "52MinutesRTS",
            "https://yt3.ggpht.com/CFOI3N-yzPTdB_e2CBurOPM8fUDE8hDZXimp9_qqBYePVxK443EXv0RW0QX0-zLrRyXWX0T69A=s160-c-k-c0x00ffffff-no-rj"),
        ch("leo-duff", "Léo Duff", "LeoDuff",
            "https://yt3.ggpht.com/ajO6plfg8hOANN2taUnHF09pfikv-SMS7uLiyH6UaULUHtm_bfGZ8qPuYTpIDJolo1sZ-fpqtBs=s160-c-k-c0x00ffffff-no-rj"),
        ch("romain-lanery", "Romain Lanéry", "RomainLanery",
            "https://yt3.ggpht.com/v2D0WfvIE1yLmfHoUZdn2dwgPiDEqAbeK5ZBXdo-ZfbZ_8db-GO9qp49wp4KtadZdZvpCf8o=s160-c-k-c0x00ffffff-no-rj"),
        ch("ego", "EGO", "EGOfficial",
            "https://yt3.ggpht.com/7wKgNZReKXMVuRP11m-o1-6yV5YU31l_BmozxJgG457ngwWSN9a02iE4YaMyKhHsDl6ViZ5uCg=s160-c-k-c0x00ffffff-no-rj"),
        ch("wartek", "Wartek", "Wartek",
            "https://yt3.ggpht.com/_ie2YptqbJLSCWuuwlo5OP5PJhzfK8VpZmFqCohUQ29qcoZQqinHwi-B9egop--weNX2LCBnYaI=s160-c-k-c0x00ffffff-no-rj"),
        ch("digidix", "Digidix", "Digidix",
            "https://yt3.ggpht.com/ytc/AIdro_n82KcQlKe4En-nmP0HmQaMfoXwvPgLYTcVOHAMfVhmdQ=s160-c-k-c0x00ffffff-no-rj"),
        ch("redbull", "Red Bull", "redbull",
            "https://yt3.googleusercontent.com/ytc/AIdro_k94J7kkxpmlJe3c2iDFJpHk8SAADPpf49cN7XjomXSzEE=s160-c-k-c0x00ffffff-no-rj"),
        ch("ted", "TED", "TED",
            "https://yt3.googleusercontent.com/ytc/AIdro_koIFcCOrvh0KThLNOiazAIDu6hcs8bjkGNwe1f6A_OYm8=s160-c-k-c0x00ffffff-no-rj"),
        ch("chef-etchebest", "Chef Etchebest", "ChefEtchebest",
            "https://yt3.googleusercontent.com/TETeWVwZ0hc-qP_wWMN74dFRRcZOipEhGJ4MegZgjgKoo47wv-9igEfwLlf2lVZx2LPCIAOO=s160-c-k-c0x00ffffff-no-rj"),
        ch("mike-horn", "Mike Horn", "MikeHornexplorer",
            "https://yt3.googleusercontent.com/ytc/AIdro_kwBn-B7PK1diHVrgMcrkufrSZJaFgXwqgxpVrCp8-z590=s160-c-k-c0x00ffffff-no-rj"),
        ch("nico-mathieux", "Nico Mathieux", "NicoMathieux",
            "https://yt3.googleusercontent.com/jQHXPSbKfrqcGVkIFNiAej1aOePweuvioSiLa7KFtRTJ1rCYX6tZfqAJyxutDJhlxfW04g4OvAM=s160-c-k-c0x00ffffff-no-rj"),
        ch("cyprien", "Cyprien", "cyprien",
            "https://yt3.googleusercontent.com/ytc/AIdro_kKiE1Vpd2RZMv057AzKdHBtqkL7ksZhZ4Huwfbr9ngUyU=s160-c-k-c0x00ffffff-no-rj"),
        ch("tibo-in-shape", "Tibo In Shape", "TiboInShape",
            "https://yt3.googleusercontent.com/MXKYsX4ryzhIwTLMwBUvx6eoWMcaF-gsHO_PLidZMEKyFj-eKyg9u0IykU8uh7ejCAS9omOlyP8=s160-c-k-c0x00ffffff-no-rj"),
        ch("la-martingale", "La Martingale Media", "LaMartingaleMedia",
            "https://yt3.googleusercontent.com/RL-_X0wTfBcP59fw3T_rPm44DGNx_UPA72Lesbb7lOrz8k4PmsCIe8h6CJdOvTkc8uxIFvTKHg=s160-c-k-c0x00ffffff-no-rj"),
        ch("zack-nani", "Zack Nani", "ZackNani",
            "https://yt3.googleusercontent.com/ytc/AIdro_kDPp1JFfNZw1d-bzKRR1k5CRHqWQrm74Eoxe7akk2Xsak=s160-c-k-c0x00ffffff-no-rj"),
        ch("quotidien-tmc", "Quotidien TMC", "QuotidienTMC",
            "https://yt3.googleusercontent.com/o6bCzmWzi1wi59g4SvOgfh9BswzD4VpdGe_EW-hUZPFVg_mNuEy5FJJPtemmZNe2Rp2c-g9Pyg=s160-c-k-c0x00ffffff-no-rj"),
        ch("clique-tv", "Clique TV", "CliqueTV",
            "https://yt3.googleusercontent.com/ytc/AIdro_lsILuhE-7OWkRBxKbIZYEptZxeCRSTsbr_lOFw_fg2DMU=s160-c-k-c0x00ffffff-no-rj"),
        ch("a-la-french", "A la french", "alafrench",
            "https://yt3.googleusercontent.com/yvHMSoMsGeiRDTSWj9vpiogalQrdCcE1wV96D8-5Izmvn6HxBJPcaCBDxroB_dfKB8jR-olGYg=s160-c-k-c0x00ffffff-no-rj"),
        ch("youyouu", "Youyouu", "Youyouu",
            "https://yt3.googleusercontent.com/0E9d2IOm7vtg1pS7DvvPlsbXXIHhwflfYvto1DHbNYWZaCGAERUIsyj5dKD4tzRXwpq86tYDHVc=s160-c-k-c0x00ffffff-no-rj"),
        ch("cocadmin", "Cocadmin", "cocadmin",
            "https://yt3.googleusercontent.com/YIxkspwrV9jPGhnm9owGVaFkHWWOZ4kuvYBh9b8S7pcRhuophuweM9AZuqQrkw0cDANM8pKN7w=s160-c-k-c0x00ffffff-no-rj"),
        ch("noob", "Noob", "NoobleretourOfficiel", ""),
        ch("popcorn", "Popcorn", "Popcorn-officiel",
            "https://yt3.ggpht.com/c--lELNYgWqiCWmZsdNwHVn7vj0IecE6RM_MLEnFopPnfMuE4MO0OCPyTD12cNmEvgeKdDJVew=s160-c-k-c0x00ffffff-no-rj"),
    ]
}
